version: '3.7'

services:
  angular: 
    build: tfg-elastest-sut-front
    networks: 
      sut:
        aliases: 
          - angular

  express:
    build: tfg-elastest-sut-back
    networks: 
      sut:
        aliases: 
          - express
      emulator:
        aliases: 
          - express
    depends_on: 
      - database

  database: 
    image: tfgelastest/mongodb
    networks: 
      - sut
    restart: always

networks: 
  sut:
    name: tfg-elastest_sut

  emulator:
    external:
      name: tfg-elastest_envoymesh
    
    
